version: '3.8'

services:
  love-letters:
    build: .
    container_name: love-letters
    ports:
      - "8014:8080"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
